In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500) 
merged = pd.read_csv('y = last month(without redundant).csv')

In [9]:
predy1 = pd.read_csv('submit_pred_proba_y1(threshold = 0.62).csv',header=None)

In [10]:
predy2 = pd.read_csv('submit_pred_proba_y2(threshold = 0.9).csv',header=None)

In [13]:
predy1.columns = ['y1']

In [18]:
#predy1[predy1['y1'] == 1]

In [14]:
predy2.columns = ['y2']

In [20]:
#predy2[predy2['y2'] == 1]

In [24]:
srno_series = pd.Series(merged['srno'].unique())

In [26]:
combination = pd.concat([srno_series,predy1, predy2], axis=1)

In [29]:
#combination[combination['y2']==1]

               0   y1   y2
588        96929  0.0  1.0
2684      174223  0.0  1.0
2899      180707  0.0  1.0
3174      188173  0.0  1.0
3253      190358  0.0  1.0
3320      192229  0.0  1.0
3321      192293  0.0  1.0
3324      192406  0.0  1.0
3501      198338  0.0  1.0
3556      199890  0.0  1.0
3640      201749  0.0  1.0
3702      203747  0.0  1.0
3735      205138  0.0  1.0
7484      324742  0.0  1.0
9042      458227  0.0  1.0
10525     480167  0.0  1.0
11466     497520  0.0  1.0
12467     546802  0.0  1.0
12592     550123  0.0  1.0
12722     553648  1.0  1.0
12948     569764  0.0  1.0
13195     575069  0.0  1.0
14563     600157  0.0  1.0
17168     701711  0.0  1.0
20424     887532  0.0  1.0
23181     978161  0.0  1.0
23333     984054  0.0  1.0
23448     988140  0.0  1.0
23513     990076  0.0  1.0
23549     990904  0.0  1.0
...          ...  ...  ...
233509  10972402  0.0  1.0
233526  10974354  0.0  1.0
233536  10974650  0.0  1.0
233632  10980894  0.0  1.0
233669  10983192  0.0  1.0
233744  10988862  0.0  1.0
233772  10990657  0.0  1.0
233792  10991544  0.0  1.0
233807  10992553  0.0  1.0
233808  10992612  1.0  1.0
233813  10992700  0.0  1.0
233957  11002236  0.0  1.0
233988  11004685  0.0  1.0
234035  11006866  0.0  1.0
234181  11017222  0.0  1.0
234256  11022632  0.0  1.0
234281  11024184  0.0  1.0
234342  11028210  0.0  1.0
234404  11032892  0.0  1.0
234463  11038471  0.0  1.0
234472  11039511  0.0  1.0
234619  11054450  0.0  1.0
234677  11060814  0.0  1.0
234756  11067523  0.0  1.0
234764  11068516  0.0  1.0
234825  11073923  0.0  1.0
234851  11076344  0.0  1.0
234854  11077170  0.0  1.0
234863  11077963  0.0  1.0
234884  11081235  0.0  1.0

[1073 rows x 3 columns]

In [30]:
combination.columns = ['srno','y1','y2']

In [35]:
#combination[combination['y2']==1]

In [36]:
combination.to_csv('submission.csv',index=False)